#!/usr/bin/env python
# vim:fileencoding=utf-8

# you may want change this
dest_url = 'http://img.vim-cn.com/'
import sys
import easygui

from subprocess import check_output
#from subprocess import call
args = []
for f in sys.argv[1:]:
  args.extend(['-F', 'name=@'+f])
cmd = ['curl', dest_url] + args

#sys.exit(call(" ".join(cmd) + " | xsel -ib", shell=True))

response=check_output(cmd, universal_newlines=True)
#easygui.msgbox(str(response))
easygui.codebox(text = str(response)) 

#flavor = easygui.buttonbox("确认开始上传图片到img.vim-cn.com。",choices = ['确认', '取消'] )
#if flavor=='确认':
#    call(" ".join(cmd) + " | xsel -ib", shell=True)
#    easygui.msgbox("图片地址已复制到剪贴板。")

